# Generated by Django 3.2.4 on 2021-06-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='id',
        ),
        migrations.AddField(
            model_name='video',
            name='video_id',
            field=models.CharField(default='video', max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
