# Generated by Django 3.2.4 on 2021-06-07 13:50

from django.db import migrations, models
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_video_thumbnail_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', encrypted_fields.fields.EncryptedCharField(max_length=100)),
                ('is_exhausted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'APITOKEN',
            },
        ),
    ]
